---
name: lint

on:
  push:
    branches: release
  pull_request:
    branches: release
  schedule:
    - cron: "0 13 * * *"

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version: [28.1, snapshot]

    steps:
      - uses: actions/checkout@v2
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}
      - name: Lint elisp
        run: make lint
